# Generated by Django 4.0.5 on 2022-06-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0004_alter_staff_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('quantité', models.IntegerField()),
                ('activity', models.BooleanField()),
            ],
        ),
    ]
