# Generated by Django 4.0.5 on 2022-06-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0006_alter_product_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=12)),
                ('adress', models.CharField(max_length=50)),
            ],
        ),
    ]
